### ISSUE TITLE
Update packages to address TypeScript Error

### ISSUE THREAD

**Issue by BekahHW** [BekahHW/postpartum-wellness-app#100]
**Describe the bug**
We're currently getting these errors:
`'View' cannot be used as a JSX component.`, `'Text' cannot be used as a JSX component.`

**To Reproduce**
1. Go to `ResourcesScreen`
2. Hover over the `View` and/or `Text` elements. See the warning that comes up.

[This issue](https://github.com/eslint/eslint/issues/15802) addresses the problem we're seeing here. Use that to identify the packages causing the conflicts and update the packages to remove the warnings.

**Comment by aishwarya-mali** [comment]
Hi @BekahHW, Can I take this one?

**Comment by BekahHW** [comment]
@aishwarya-mali absolutely!

**Comment by aishwarya-mali** [comment]
@BekahHW We will have to update following packages as well. Is it okay if I do that in this issue?
<img width="530" alt="image" src="https://user-images.githubusercontent.com/43086476/216780053-8db7b4b8-0489-4c94-858a-ccd76e005ec0.png">

**Comment by BekahHW** [comment]
@aishwarya-mali thats fine.
