### ISSUE TITLE
Add Affirmation Loading Screen

### ISSUE THREAD

**Issue by BekahHW** [BekahHW/postpartum-wellness-app#19]
-For when data is loading, display an affirmation. 

* In the screens folder, create a file called LoadingAffirmation.js
* copy the code from HomeScreen.js 
* Update HomeScreen to use LoadingAffirmation
* Delete buttons and navigationOptions
* Update Postpartum Wellness text to "I am a powerhouse; I am indestructible."

For later update: Here are some good affirmations for faked data: https://www.huffpost.com/entry/affirmations_b_3527028.

**Comment by vanessacor** [comment]
I want to have go with this one

**Comment by BekahHW** [comment]
Awesome, Vanessa! Let me know if you have questions.
