### ISSUE TITLE
Change onPress for SignUpScreen

### ISSUE THREAD

**Issue by BekahHW** [BekahHW/postpartum-wellness-app#20]
## Where
screens > SignUpScreen

## What
The onPress currently navigates to the HomeScreen. Instead, when the button is pressed, this message should be displayed, "Thank you for signing up! Please check your email for verification."

## How
It might make sense to add state here [signedUp, setSignedUp] = useState(false) and then the onPress changes the state to true. Using a ternary, display the Thank you message in a text component instead of the text and text inputs that are currently displayed.

**Comment by torianne02** [comment]
I can give this one a whirl.

**Comment by BekahHW** [comment]
Awesome @torianne02 ! It's all yours. Let me know if you have questions.

**Comment by norafergany** [comment]
@BekahHW I think I'm ready to submit my pull request! I read CONTRIBUTING.md and forked the repo. Do you want the changes to be made on a topic branch with a specific naming format (e.g. `norafergany/sign-up-message`) ?

**Comment by BekahHW** [comment]
@norafergany `norafergany/sign-up-message` would be great! I'm not really particular right now since I don't have a huge number of PRs. Thanks for asking!
