### ISSUE TITLE
DayPromptScreen needs updated to work with current version

### ISSUE THREAD

**Issue by BekahHW** [BekahHW/postpartum-wellness-app#22]
## What
An error on the page is preventing it from loading.

## Where
DayPromptScreen.tsx

## Why
This project was left in a dusty corner for a while and in updating everything, the current page is not loading. I haven't had time to look at what the problem is, but it was originally a js file and now is using tsx, and that's been a recurring update I've needed to make. 

Basically, the goal is to get the page working

**Comment by juddey** [comment]
Hey Bekah!

I cloned the repo, set everything up etc, etc, hooked up the DayPromptScreen to the router, uncommented the code, and got this....
![image](https://user-images.githubusercontent.com/7445602/96212239-cc4bca80-0fd2-11eb-8ef9-3789b3da7d9a.png)

Which didn't seem to match with the "current page is not loading" description....

Did I miss something?

**Comment by BekahHW** [comment]
First of all, thanks for checking this out.

Second, I don't know why that says terrible, because that is not the best word choice. So that will need updated. I'm wondering if we should do something like this 

![image](https://user-images.githubusercontent.com/34313413/96240330-c3c1a880-0f6e-11eb-8041-58b34ebb3ceb.png)

I read that people are more likely to rate their mood if it includes emojis.

But I can put that in a separate issue.

Could you commit and push your changes so I can take a look? Maybe it has to do with updating the navigation that I was using.

**Comment by juddey** [comment]
Hey Bekah....  Following up from todays discussion with @tkshill I think it makes sense to close this issue out, the daypromptscreen is gonna look a lot different now, and its not really a candidate for a radiobutton component anymore.

What do you think?

**Comment by BekahHW** [comment]
@juddey yep. You're right. Closing this in anticipation of something new tomorrow. Thank you for helping me through this 🥰
