### ISSUE TITLE
Create Profile Screen not loading right

### ISSUE THREAD

**Issue by BekahHW** [BekahHW/postpartum-wellness-app#23]
## Where
screens > CreateProfileScreen.tsx

## What
What should be a form is currently 
![image](https://user-images.githubusercontent.com/34313413/94345361-4e0f9000-fff3-11ea-8be8-39b63c128acd.png)

## Why
Best guess is that there is something going on with the styles

To see the screen, run` yarn ios` and then click the profile button in the bottom right.

**Comment by aurelieverrot** [comment]
Hi! I'll work on this :)
