### ISSUE TITLE
Add React-native-testing-library and write first test

### ISSUE THREAD

**Issue by BekahHW** [BekahHW/postpartum-wellness-app#25]
**Add testing library**
To ensure that the app is working for users.

**Describe the solution you'd like**
Allow tests to be written with RNTL to ensure things are working right.

**Additional context**
You can find directions starting[ here](https://testing-library.com/docs/react-native-testing-library/intro) 

**Adding First Test**
-Keep it simple just to ensure it's working. 
-test `HomeScreen.tsx` to ensure Sign-In and Sing-Up buttons are visible.

**Comment by nickytonline** [comment]
I've never done any React native, but I'd still like to tackle this. Can you assign this issue to me @BekahHW?

**Comment by BekahHW** [comment]
Thanks, Nick. It's all yours. Let me know if you have questions.
