### ISSUE TITLE
Update button navigation on HomeScreen.tsx

### ISSUE THREAD

**Issue by BekahHW** [BekahHW/postpartum-wellness-app#26]
**Navigate to correct paths in HomeScreen.tsx**
Currently the paths are navigation to root as default and need to be updated.

**Describe the solution you'd like**
- Sign-In button needs to navigate to SignInScreen.tsx
- Sign-up button needs to navigate to SignUpScreen.tsx

**Additional context**
-[These docs](https://reactnavigation.org/docs/stack-navigator/) might be helpful

**Comment by honsq90** [comment]
I can work on this :)
