### ISSUE TITLE
Update CreateProfileScreen by adding switch for boolean state variables

### ISSUE THREAD

**Issue by BekahHW** [BekahHW/postpartum-wellness-app#30]
Depends on issue #23 

**Issue**
The form is currently incomplete. `supportNetwork` and `breastfeeding` variables need boolean inputs 

**Describe the solution you'd like**
- This for reference https://reactnative.dev/docs/switch.html
- Delete the device Background color

For `supportNetwork`, ask whether or not the user feels supported as a parent by someone close to her in a yes/no toggle
- This for reference https://reactnative.dev/docs/switch.html
- instead of isEnabled, use` supportNetwork`
- instead of` setIsEnabled`, use setSupportNetwork

For `breastfeeding,` ask whether or not the user feels supported as a parent by someone close to her in a yes/no toggle
- This for reference https://reactnative.dev/docs/switch.html
- instead of isEnabled, use breastfeeding
- instead of `setIsEnabled`, use `setBreastfeeding`

**To test**
With the app running, click the profile button in the bottom right. This will take you to the `CreateProfileScreen`, where you should see all your changes.

**Comment by vanessacor** [comment]
I can do this one!
