### ISSUE TITLE
Add Resource Links for postpartum care for moms

### ISSUE THREAD

**Issue by BekahHW** [BekahHW/postpartum-wellness-app#32]
**Add more resources for moms**
Right now there's only one resource

**Describe the solution you'd like**
-Find 3 or 4 reputable resources to add
-Copy the current resource and update the URL and Text according to your resource
```

 <Text
            style={styles.linkText}
            onPress={() =>
              Linking.openURL(
                "This is where the link goes"
              )
            }
          >
            This is the title of your resource
          </Text>
```

**To view your changes**
Run the app and click the resources link in the center of the bottom nav

**Comment by vanessacor** [comment]
Can I take this issue?

**Comment by BekahHW** [comment]
Yes! I just pushed a couple of changes. So you might need to update what you have.
