### ISSUE TITLE
Add Resource Links for Dads

### ISSUE THREAD

**Issue by BekahHW** [BekahHW/postpartum-wellness-app#33]
**Add more resources for dads**
Right now there's only one resource for dads during the postpartum phase.

**Describe the solution you'd like**
-Find 3 or 4 reputable resources to add
-Copy the current resource and update the URL and Text according to your resource
```

 <Text
            style={styles.linkText}
            onPress={() =>
              Linking.openURL(
                "This is where the link goes"
              )
            }
          >
            This is the title of your resource
          </Text>
```

**To view your changes**
Run the app and click the resources link in the center of the bottom nav

**Comment by maylenepoulsen** [comment]
Hi Bekah, working on Hacktoberfest is the top of my list today! Could I work on this issue please?

**Comment by BekahHW** [comment]
Absolutely! I pushed up some changes the last couple of days, so if you cloned it a while ago, you might want to grab what's there now.

**Comment by regromrob** [comment]
Hey Bekah, how many resources for dads would you like inputed and will you need to verify these resources before hand?
