### ISSUE TITLE
Add a mindfulness screen

### ISSUE THREAD

**Issue by BekahHW** [BekahHW/postpartum-wellness-app#56]
We have the positivity toolbox, and now we need to add some activities for each of the "tools." This is for the Mindfulness Screen.

## Steps
_I need to add some thoughts on design, but for now, it needs to stay consistent with the colors and fonts we've been using._
- [ ] Create a file called MindfulnessScreen
- [ ] For this screen, let's start by hard-coding this mindfulness activity:
       - "Let's be present at this moment through all of our senses: What do you hear? What do you see? What can you taste? 
       What can you smell? What can you feel?"
- [ ] In the positivity toolbox, add this to the path for the mindfulness card.

**Comment by adiati98** [comment]
Hi @BekahHW,
I'm not familiar yet with React/React Native 😁, but may I try this one? 😊

**Comment by aishwarya-mali** [comment]
@BekahHW I would like to work on this. Can you assign this screen to me?

**Comment by BekahHW** [comment]
Thanks, @aishwarya-mali!
