### ISSUE TITLE
Friend Screen

### ISSUE THREAD

**Issue by BekahHW** [BekahHW/postpartum-wellness-app#57]
Connection is a really important part of getting help when you need it. This screen should ask for contact information for a friend, partner, or a family member in case the mom needs support. The default number for US moms should be SAMHSA’s National Helpline, 1-800-662-HELP (4357).

## Steps
- [ ] Create ContactFriendsScreen.tsx in the Screens Folder
- [ ] Add a Text Component: Connection for when you need it most.
- [ ] Add a placeholder image--once we settle on a design this will be replaced.
- [ ] Add a Text Component: Sometimes life can get hard fast. Staying connected with others can help. Add the phone number of a friend, partner, or a family member if you need to connect easily. (We'll never share this information. It is for your use only.)
- [ ] Input for contact name and an input for contact number.
- [ ] Add a save button with touchable opacity. For the onPress, console log the values of the input and contact number.

**Comment by arvinf07** [comment]
Hey Im trying to run it on my web browsed and It's missing a AffirmationsScreen file. Are you familiar with this error.

**Comment by BekahHW** [comment]
@arvinf07 I don't think it needs to be. 

But, 1- I put whatever I'm using in the bottomtabnavigator to easily test; 2- If you think it should be, I'm up for hearing more.

**Comment by arvinf07** [comment]
@BekahHW I'll try that out and see how it looks. I see one of the steps is to add a placeholder image, where should that be placed?
