### ISSUE TITLE
Add Back navigation to header

### ISSUE THREAD

**Issue by BekahHW** [BekahHW/postpartum-wellness-app#71]
**Is your feature request related to a problem? Please describe.**
There's no back button 😭 

**Describe the solution you'd like**
At the top left of the screen add a back arrow to navigate back
**Ideas**
- [.goBack( ) function](https://reactnavigation.org/docs/navigation-prop/)
- history prop

**Context**
- We're using [React Navigation](https://reactnavigation.org/docs/navigation-prop/) and [BottomTabNavigator](https://reactnavigation.org/docs/bottom-tab-navigator/)

**Comment by nicoolel** [comment]
hi bekah, i'd like to be more familiar with react and react native. may i be assigned this issue?
