### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by JesseRWeigel** [BekahHW/postpartum-wellness-app#90]
**Is your feature request related to a problem? Please describe.**
It is now standard practice to use `main` instead of `master` for branch naming.

**Describe the solution you'd like**
I would like the name to be changed to `main`.

**Describe alternatives you've considered**
I suppose you could name it anything you want (`primary`, `frank`, `pineapple`) but the least confusing choice would be `main`.

**Additional context**
[https://github.com/github/renaming](https://github.com/github/renaming)

**Comment by BekahHW** [comment]
Thanks, @JesseRWeigel. All updated.
