### ISSUE TITLE
Add a Profile Screen

### ISSUE THREAD

**Issue by BekahHW** [BekahHW/postpartum-wellness-app#93]
There's currently a screen file called `ProfileScreen.tsx`. Because we don't have anything set up for login right now, let's get the design in there and hardcode what needs to be there. 

- User picture - rounded border
- days in a row tracked
- get support -> `<Button>` that immediately sends a message to support system. For now console.log('text a friend')
 Get help now -> For now console.log('help now')

I'm thinking something like this for the top of profile screen, but I'm up for suggestions.
![image](https://user-images.githubusercontent.com/34313413/193290175-b94f73f1-f30f-4f8c-8e5f-6a83533cb285.png)

**Comment by dominicduffin1** [comment]
I can work on this during October!

**Comment by BekahHW** [comment]
@dominicduffin1 I'm sorry I never responded to this! I went ahead and assigned you, but if you can't do it anymore, let me know.
