### ISSUE TITLE
Sign-up Screen: Entering text in "Password" field also fills "Re-enter Password" field

### ISSUE THREAD

**Issue by dmahajan980** [BekahHW/postpartum-wellness-app#95]
**Describe the bug**
On the **Sign-up** screen, entering a password in the _Password_ field also fills up the _Re-enter password for validation_ field (see **Video** below).

**To Reproduce**
1. Go to **Home** tab and press **Sign-up** button to open the Sign-up screen.
2. Enter the password in the **Password** field. Notice that the **Re-enter password for validation** field also changes as you type in the password.

**Expected behavior**
The **Re-enter password for validation** should be independent of **Password** field. Although the value in both fields should match, the user should fill these fields separately.

**Video**

https://user-images.githubusercontent.com/37256767/193408196-d72605a7-d6f9-4f85-ad73-0a3b27662fc4.mp4

**Smartphone:**
 - Device: iPhone 13 Pro Max
 - OS: iOS 15.5
 - Version: 1.0.0

**Comment by BekahHW** [comment]
@rokkoo I'll assign this to you.
